version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    container_name: mysql_egh455
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sensors
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
